.PHONY: clean All

All:
	@echo "----------Building project:[ LaboratorioC__main - Debug ]----------"
	@"$(MAKE)" -f  "LaboratorioC__main.mk"
clean:
	@echo "----------Cleaning project:[ LaboratorioC__main - Debug ]----------"
	@"$(MAKE)" -f  "LaboratorioC__main.mk" clean
